# build
#    docker compose --env-file corid_env build --with-dependencies 
# run
#    docker compose --env-file corid_env up 


name: $CORID_ENV-cor-id_v2


services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    image: massivecapybara/corid_api:latest
    ports:
      - "$CORID_API_PORT:8000"
    depends_on:
      - prometheus
      - postgres
    env_file:
      - $CORID_ENV-corid.cor-medical.ua.env

  redis:
    image: redis:alpine
    ports:
      - $CORID_REDIS_PORT:6379


  postgres:
    image: postgres:latest
    env_file:
      - $CORID_ENV-corid.cor-medical.ua.env
    ports:
      - $CORID_POSTGRES_PORT:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - $CORID_PROMETEUS_PORT:9090

  grafana:
    image: grafana/grafana:latest
    ports:
      - $CORID_GRAFANA_PORT:3000
    depends_on:
      - loki

  loki:
    image: grafana/loki:latest
    ports:
      - $CORID_LOKI_PORT:3100
    command: -config.file=/etc/loki/local-config.yaml
    user: "0:0"
    volumes:
      - ./loki-config.yaml:/etc/loki/loki-config.yaml
      - ./:/app
      - loki-data:/wal
      - compactor-data:/tmp/loki/compactor

  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/log:/var/log
      - ./:/app
      - ./promtail-config.yaml:/etc/promtail/config.yaml
    command: -config.file=/etc/promtail/config.yaml
    depends_on:
      - loki

volumes:
  postgres_data:
  grafana-storage:
  loki-data:
  compactor-data:
