"""add glass scan url  v1.1.9

Revision ID: 00b73b2e1010
Revises: 256d042dee23
Create Date: 2025-08-13 10:50:49.405303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00b73b2e1010'
down_revision: Union[str, None] = '256d042dee23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('glasses', sa.Column('scan_url', sa.String(), nullable=True))
    op.add_column('glasses', sa.Column('preview_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('glasses', 'preview_url')
    op.drop_column('glasses', 'scan_url')
    # ### end Alembic commands ###
