"""add patient clinic status  v1.0.0.43

Revision ID: 011fe341a511
Revises: d4eea16b7a69
Create Date: 2025-06-13 10:35:13.785730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '011fe341a511'
down_revision: Union[str, None] = 'd4eea16b7a69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinic_patient_statuses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('patient_status_for_clinic', sa.Enum('registered', 'diagnosed', 'under_treatment', 'hospitalized', 'discharged', 'died', 'in_process', 'referred_for_additional_consultation', 'awaiting_report', 'completed', 'error', name='patientclinicstatus'), nullable=True),
    sa.Column('assigned_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clinic_patient_statuses')
    # ### end Alembic commands ###
