"""update doctor  models, delete relationships  v1.0.0.24

Revision ID: 063cb9f9ee31
Revises: 5055df5b5936
Create Date: 2025-05-09 12:23:03.511170

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "063cb9f9ee31"
down_revision: Union[str, None] = "5055df5b5936"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
