"""add case reports and doctors signups  v1.0.0.40

Revision ID: 06effa04a3ff
Revises: 7777cdb243ab
Create Date: 2025-06-09 14:56:16.444748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06effa04a3ff'
down_revision: Union[str, None] = '7777cdb243ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('immunohistochemical_profile', sa.Text(), nullable=True),
    sa.Column('molecular_genetic_profile', sa.Text(), nullable=True),
    sa.Column('pathomorphological_diagnosis', sa.Text(), nullable=True),
    sa.Column('icd_code', sa.String(length=50), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('attached_glass_ids', sa.ARRAY(sa.String(length=36)), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_table('doctor_signatures',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('signature_name', sa.String(length=255), nullable=True),
    sa.Column('signature_scan_data', sa.LargeBinary(), nullable=True),
    sa.Column('signature_scan_type', sa.String(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_signatures',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('doctor_signature_id', sa.String(length=36), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['doctor_signature_id'], ['doctor_signatures.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_signatures')
    op.drop_table('doctor_signatures')
    op.drop_table('reports')
    # ### end Alembic commands ###
