"""add biomaterial date and case close date v1.0.12

Revision ID: 071c61bdfd9a
Revises: a2da3b6c7aa5
Create Date: 2025-07-03 14:05:54.764050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '071c61bdfd9a'
down_revision: Union[str, None] = 'a2da3b6c7aa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('closing_date', sa.DateTime(), nullable=True))
    op.add_column('referrals', sa.Column('biomaterial_date', sa.DateTime(), nullable=True, comment='Дата забора биоматериала'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('referrals', 'biomaterial_date')
    op.drop_column('cases', 'closing_date')
    # ### end Alembic commands ###
