"""update doctor and documents models  v1.0.0.25

Revision ID: 09b13b7119be
Revises: 063cb9f9ee31
Create Date: 2025-05-09 12:55:19.923209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '09b13b7119be'
down_revision: Union[str, None] = '063cb9f9ee31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificates', sa.Column('file_data', sa.LargeBinary(), nullable=True))
    op.add_column('certificates', sa.Column('file_type', sa.String(), nullable=True))
    op.drop_column('certificates', 'scan')
    op.add_column('diplomas', sa.Column('file_data', sa.LargeBinary(), nullable=True))
    op.add_column('diplomas', sa.Column('file_type', sa.String(), nullable=True))
    op.drop_column('diplomas', 'scan')
    op.add_column('doctors', sa.Column('reserv_scan_data', sa.LargeBinary(), nullable=True))
    op.add_column('doctors', sa.Column('reserv_scan_file_type', sa.String(), nullable=True))
    op.drop_column('doctors', 'reserv_scan')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('reserv_scan', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('doctors', 'reserv_scan_file_type')
    op.drop_column('doctors', 'reserv_scan_data')
    op.add_column('diplomas', sa.Column('scan', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('diplomas', 'file_type')
    op.drop_column('diplomas', 'file_data')
    op.add_column('certificates', sa.Column('scan', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('certificates', 'file_type')
    op.drop_column('certificates', 'file_data')
    # ### end Alembic commands ###
