"""update device  models  v1.0.0.22

Revision ID: 0acd5a1b4a9e
Revises: c6f342d88e9b
Create Date: 2025-05-05 15:15:11.520078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0acd5a1b4a9e'
down_revision: Union[str, None] = 'c6f342d88e9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Удаляем существующий внешний ключ
    op.drop_constraint('device_access_device_id_fkey', 'device_access', type_='foreignkey')

    # Изменяем тип столбца id в таблице device_access
    op.alter_column('device_access', 'id',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(length=36),
                    existing_nullable=False)
    op.alter_column('device_access', 'device_id',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(length=36),  # Важно указать длину, если id в devices имеет длину
                    existing_nullable=True)
    # op.create_index(op.f('ix_device_access_id'), 'device_access', ['id'], unique=False)

    op.add_column('devices', sa.Column('serial_number', sa.String(), nullable=True))
    op.alter_column('devices', 'id',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(length=36),
                    existing_nullable=False,
                    existing_server_default=sa.text("nextval('devices_id_seq'::regclass)"))
    # op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)
    # op.create_index(op.f('ix_devices_token'), 'devices', ['token'], unique=True)
    op.create_foreign_key(None, 'devices', 'manufactured_devices', ['serial_number'], ['serial_number'])

    op.alter_column('manufactured_devices', 'id',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(length=36),
                    existing_nullable=False)
    # op.create_index(op.f('ix_manufactured_devices_id'), 'manufactured_devices', ['id'], unique=False)
    # op.create_index(op.f('ix_manufactured_devices_token'), 'manufactured_devices', ['token'], unique=True)

    # Создаем новый внешний ключ
    op.create_foreign_key('device_access_device_id_fkey', 'device_access', 'devices', ['device_id'], ['id'])
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('device_access_device_id_fkey', 'device_access', type_='foreignkey')
    op.drop_index(op.f('ix_manufactured_devices_token'), 'manufactured_devices')
    op.drop_index(op.f('ix_manufactured_devices_id'), 'manufactured_devices')
    op.alter_column('manufactured_devices', 'id',
                    existing_type=sa.String(length=36),
                    type_=sa.INTEGER(),
                    existing_nullable=False)
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.drop_index(op.f('ix_devices_token'), 'devices')
    op.drop_index(op.f('ix_devices_id'), 'devices')
    op.alter_column('devices', 'id',
                    existing_type=sa.String(length=36),
                    type_=sa.INTEGER(),
                    existing_nullable=False,
                    existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False))
    op.drop_column('devices', 'serial_number')
    op.drop_index(op.f('ix_device_access_id'), 'device_access')
    op.alter_column('device_access', 'device_id',
                    existing_type=sa.String(),
                    type_=sa.INTEGER(),
                    existing_nullable=True)
    op.alter_column('device_access', 'id',
                    existing_type=sa.String(length=36),
                    type_=sa.INTEGER(),
                    existing_nullable=False)
    op.create_foreign_key('device_access_device_id_fkey', 'device_access', 'devices', ['device_id'], ['id'])
    # ### end Alembic commands ###
    # ### end Alembic commands ###
