"""fix case_owner column v1.0.7

Revision ID: 0afcb3cae59b
Revises: 5a87ae883a42
Create Date: 2025-06-23 14:32:18.284643

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0afcb3cae59b"
down_revision: Union[str, None] = "5a87ae883a42"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("cases_case_owner_fkey", "cases", type_="foreignkey")
    op.create_foreign_key(None, "cases", "doctors", ["case_owner"], ["doctor_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "cases", type_="foreignkey")
    op.create_foreign_key(
        "cases_case_owner_fkey", "cases", "doctors", ["case_owner"], ["id"]
    )
    # ### end Alembic commands ###
