"""add soc  v1.1.6

Revision ID: 15d6aa4a9e45
Revises: 7a07fa844f6d
Create Date: 2025-07-23 11:50:24.969462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15d6aa4a9e45'
down_revision: Union[str, None] = '7a07fa844f6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cerbo_measurements', sa.Column('soc', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cerbo_measurements', 'soc')
    # ### end Alembic commands ###
