"""fix create date to patient v1.0.0.11

Revision ID: 162691655122
Revises: 2147cd801160
Create Date: 2025-04-23 12:51:46.836143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '162691655122'
down_revision: Union[str, None] = '2147cd801160'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('create_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'create_date')
    # ### end Alembic commands ###
