"""Test migration for prod v1.0.1

Revision ID: 1b3b51eb648d
Revises: 3bccc3564955
Create Date: 2025-06-17 11:09:41.833166

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1b3b51eb648d"
down_revision: Union[str, None] = "3bccc3564955"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
