"""Fix doctor documents  model v1.0.0.6

Revision ID: 1c9da8339f0e
Revises: 63aebf60cf27
Create Date: 2025-03-21 09:49:05.326504

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1c9da8339f0e"
down_revision: Union[str, None] = "63aebf60cf27"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "certificates_doctor_id_fkey", "certificates", type_="foreignkey"
    )
    op.create_foreign_key(None, "certificates", "doctors", ["doctor_id"], ["doctor_id"])
    op.drop_constraint(
        "clinic_affiliations_doctor_id_fkey", "clinic_affiliations", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "clinic_affiliations", "doctors", ["doctor_id"], ["doctor_id"]
    )
    op.drop_constraint("diplomas_doctor_id_fkey", "diplomas", type_="foreignkey")
    op.create_foreign_key(None, "diplomas", "doctors", ["doctor_id"], ["doctor_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "diplomas", type_="foreignkey")
    op.create_foreign_key(
        "diplomas_doctor_id_fkey", "diplomas", "doctors", ["doctor_id"], ["id"]
    )
    op.drop_constraint(None, "clinic_affiliations", type_="foreignkey")
    op.create_foreign_key(
        "clinic_affiliations_doctor_id_fkey",
        "clinic_affiliations",
        "doctors",
        ["doctor_id"],
        ["id"],
    )
    op.drop_constraint(None, "certificates", type_="foreignkey")
    op.create_foreign_key(
        "certificates_doctor_id_fkey", "certificates", "doctors", ["doctor_id"], ["id"]
    )
    # ### end Alembic commands ###
