"""add referral other study type  v1.1.8

Revision ID: 256d042dee23
Revises: eb10eade2363
Create Date: 2025-08-12 14:54:39.056522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '256d042dee23'
down_revision: Union[str, None] = 'eb10eade2363'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE studytype ADD VALUE 'OTHER'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TYPE studytype DROP VALUE 'OTHER'"
    )  
    # ### end Alembic commands ###
