"""add energy manager table  v1.0.0.44

Revision ID: 2680e0d4b6d4
Revises: 011fe341a511
Create Date: 2025-06-13 13:24:54.471242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2680e0d4b6d4'
down_revision: Union[str, None] = '011fe341a511'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('energy_managers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('energy_manager_cor_id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('surname', sa.String(length=100), nullable=True),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('lab_assistants_photo', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['energy_manager_cor_id'], ['users.cor_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('energy_manager_cor_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('energy_managers')
    # ### end Alembic commands ###
