"""update doctor_diagnosis table v1.0.5

Revision ID: 28a3a23353f5
Revises: be97999f4c62
Create Date: 2025-06-23 11:45:42.724327

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "28a3a23353f5"
down_revision: Union[str, None] = "be97999f4c62"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "doctor_diagnoses", sa.Column("icd_code", sa.String(length=50), nullable=True)
    )
    op.add_column("doctor_diagnoses", sa.Column("comment", sa.Text(), nullable=True))
    op.add_column(
        "doctor_diagnoses",
        sa.Column("report_macrodescription", sa.Text(), nullable=True),
    )
    op.add_column(
        "doctor_diagnoses",
        sa.Column("report_microdescription", sa.Text(), nullable=True),
    )
    op.drop_column("reports", "icd_code")
    op.drop_column("reports", "comment")
    op.drop_column("reports", "report_macrodescription")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reports",
        sa.Column(
            "report_macrodescription", sa.TEXT(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "reports", sa.Column("comment", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "reports",
        sa.Column(
            "icd_code", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("doctor_diagnoses", "report_microdescription")
    op.drop_column("doctor_diagnoses", "report_macrodescription")
    op.drop_column("doctor_diagnoses", "comment")
    op.drop_column("doctor_diagnoses", "icd_code")
    # ### end Alembic commands ###
