"""add glass count to cassette v1.0.0.17

Revision ID: 2e2be028f1e8
Revises: 9fe4ae4b3fec
Create Date: 2025-04-29 13:20:06.397591

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2e2be028f1e8"
down_revision: Union[str, None] = "9fe4ae4b3fec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cassettes", sa.Column("glass_count", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cassettes", "glass_count")
    # ### end Alembic commands ###
