"""updat OphthalmologicalPrescription table  v1.1.21

Revision ID: 3494ffbd8c8b
Revises: faf1a35189f5
Create Date: 2025-10-09 10:57:43.086343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3494ffbd8c8b'
down_revision: Union[str, None] = 'faf1a35189f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ophthalmological_prescriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('od_sph', sa.Float(), nullable=True),
    sa.Column('od_cyl', sa.Float(), nullable=True),
    sa.Column('od_ax', sa.Float(), nullable=True),
    sa.Column('od_prism', sa.Float(), nullable=True),
    sa.Column('od_base', sa.String(length=10), nullable=True),
    sa.Column('od_add', sa.Float(), nullable=True),
    sa.Column('os_sph', sa.Float(), nullable=True),
    sa.Column('os_cyl', sa.Float(), nullable=True),
    sa.Column('os_ax', sa.Float(), nullable=True),
    sa.Column('os_prism', sa.Float(), nullable=True),
    sa.Column('os_base', sa.String(length=10), nullable=True),
    sa.Column('os_add', sa.Float(), nullable=True),
    sa.Column('glasses_purpose', sa.String(length=50), nullable=False),
    sa.Column('glasses_type', sa.String(length=50), nullable=False),
    sa.Column('issue_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('term_months', sa.Float(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('doctor_signature_id', sa.String(length=36), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_signature_id'], ['doctor_signatures.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ophthalmological_prescriptions_patient_id'), 'ophthalmological_prescriptions', ['patient_id'], unique=False)
    op.drop_index('ix_ophthalmological_prescription_patient_id', table_name='ophthalmological_prescription')
    op.drop_table('ophthalmological_prescription')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ophthalmological_prescription',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('od_sph', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('od_cyl', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('od_ax', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('od_prism', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('od_base', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('od_add', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('os_sph', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('os_cyl', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('os_ax', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('os_prism', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('os_base', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('os_add', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('glasses_purpose', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('glasses_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('note', sa.VARCHAR(length=350), autoincrement=False, nullable=False),
    sa.Column('doctor_signature_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('signed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['doctor_signature_id'], ['doctor_signatures.id'], name='ophthalmological_prescription_doctor_signature_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='ophthalmological_prescription_pkey')
    )
    op.create_index('ix_ophthalmological_prescription_patient_id', 'ophthalmological_prescription', ['patient_id'], unique=False)
    op.drop_index(op.f('ix_ophthalmological_prescriptions_patient_id'), table_name='ophthalmological_prescriptions')
    op.drop_table('ophthalmological_prescriptions')
    # ### end Alembic commands ###
