"""add medicines and firstaid kit tables  v1.1.17

Revision ID: 398070ad6677
Revises: fa39f9edfd59
Create Date: 2025-10-06 14:05:16.975009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '398070ad6677'
down_revision: Union[str, None] = 'fa39f9edfd59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('active_substance', sa.String(length=255), nullable=True),
    sa.Column('intake_method', sa.String(length=100), nullable=True),
    sa.Column('dosage', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('concentration', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_medicines_name', 'medicines', ['name'], unique=False)
    op.create_table('first_aid_kits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_cor_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_cor_id'], ['users.cor_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_first_aid_kits_user_cor_id', 'first_aid_kits', ['user_cor_id'], unique=False)
    op.create_table('medicine_schedules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('medicine_id', sa.String(length=36), nullable=False),
    sa.Column('user_cor_id', sa.String(length=36), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('times_per_day', sa.Integer(), nullable=True),
    sa.Column('intake_times', sa.String(length=255), nullable=True),
    sa.Column('interval_minutes', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_cor_id'], ['users.cor_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_medicine_schedules_medicine_id', 'medicine_schedules', ['medicine_id'], unique=False)
    op.create_index('idx_medicine_schedules_user_cor_id', 'medicine_schedules', ['user_cor_id'], unique=False)
    op.create_table('first_aid_kit_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('first_aid_kit_id', sa.String(length=36), nullable=False),
    sa.Column('medicine_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['first_aid_kit_id'], ['first_aid_kits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_first_aid_kit_items_kit_id', 'first_aid_kit_items', ['first_aid_kit_id'], unique=False)
    op.create_index('idx_first_aid_kit_items_medicine_id', 'first_aid_kit_items', ['medicine_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_first_aid_kit_items_medicine_id', table_name='first_aid_kit_items')
    op.drop_index('idx_first_aid_kit_items_kit_id', table_name='first_aid_kit_items')
    op.drop_table('first_aid_kit_items')
    op.drop_index('idx_medicine_schedules_user_cor_id', table_name='medicine_schedules')
    op.drop_index('idx_medicine_schedules_medicine_id', table_name='medicine_schedules')
    op.drop_table('medicine_schedules')
    op.drop_index('idx_first_aid_kits_user_cor_id', table_name='first_aid_kits')
    op.drop_table('first_aid_kits')
    op.drop_index('idx_medicines_name', table_name='medicines')
    op.drop_table('medicines')
    # ### end Alembic commands ###
