"""Initial migration for prod v1.0.0

Revision ID: 3bccc3564955
Revises: 
Create Date: 2025-06-17 11:06:24.504775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bccc3564955'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('case_code', sa.String(length=250), nullable=True),
    sa.Column('bank_count', sa.Integer(), nullable=True),
    sa.Column('cassette_count', sa.Integer(), nullable=True),
    sa.Column('glass_count', sa.Integer(), nullable=True),
    sa.Column('grossing_status', sa.Enum('PROCESSING', 'COMPLETED', name='grossing_status'), nullable=True),
    sa.Column('pathohistological_conclusion', sa.Text(), nullable=True),
    sa.Column('microdescription', sa.Text(), nullable=True),
    sa.Column('general_macrodescription', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_case_code'), 'cases', ['case_code'], unique=True)
    op.create_index(op.f('ix_cases_patient_id'), 'cases', ['patient_id'], unique=False)
    op.create_table('cor_id_auth_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('cor_id', sa.String(length=250), nullable=True),
    sa.Column('session_token', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'TIMEOUT', name='authsessionstatus'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cor_id_auth_sessions_token', 'cor_id_auth_sessions', ['session_token'], unique=False)
    op.create_index(op.f('ix_cor_id_auth_sessions_cor_id'), 'cor_id_auth_sessions', ['cor_id'], unique=False)
    op.create_index(op.f('ix_cor_id_auth_sessions_email'), 'cor_id_auth_sessions', ['email'], unique=False)
    op.create_index(op.f('ix_cor_id_auth_sessions_session_token'), 'cor_id_auth_sessions', ['session_token'], unique=True)
    op.create_table('manufactured_devices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('MANUFACTURED', 'ACTIVATED', 'BLOCKED', name='devicestatus'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_index(op.f('ix_manufactured_devices_id'), 'manufactured_devices', ['id'], unique=False)
    op.create_index(op.f('ix_manufactured_devices_token'), 'manufactured_devices', ['token'], unique=True)
    op.create_table('printing_device',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('device_class', sa.String(), nullable=False),
    sa.Column('device_identifier', sa.String(), nullable=False),
    sa.Column('subnet_mask', sa.String(), nullable=True),
    sa.Column('gateway', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_identifier')
    )
    op.create_index(op.f('ix_printing_device_id'), 'printing_device', ['id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_tags_name', 'tags', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cor_id', sa.String(length=250), nullable=True),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('backup_email', sa.String(length=250), nullable=True),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('last_password_change', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('access_token', sa.String(length=500), nullable=True),
    sa.Column('refresh_token', sa.String(length=500), nullable=True),
    sa.Column('recovery_code', sa.LargeBinary(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('premium', 'basic', name='status'), nullable=True),
    sa.Column('unique_cipher_key', sa.String(length=250), nullable=False),
    sa.Column('user_sex', sa.String(length=10), nullable=True),
    sa.Column('birth', sa.Integer(), nullable=True),
    sa.Column('user_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('backup_email'),
    sa.UniqueConstraint('cor_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_index')
    )
    op.create_index('idx_users_cor_id', 'users', ['cor_id'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_table('verification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('verification_code', sa.Integer(), nullable=True),
    sa.Column('email_confirmation', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_verification_email', 'verification', ['email'], unique=False)
    op.create_table('case_parameters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('macro_archive', sa.Enum('ESS', 'RSS', name='macroarchive'), nullable=True),
    sa.Column('decalcification', sa.Enum('ABSENT', 'EDTA', 'ACIDIC', name='decalcificationtype'), nullable=True),
    sa.Column('sample_type', sa.Enum('NATIVE', 'BLOCKS', name='sampletype'), nullable=True),
    sa.Column('material_type', sa.Enum('R', 'B', 'E', 'C', 'CB', 'S', 'A', 'EM', name='materialtype'), nullable=True),
    sa.Column('urgency', sa.Enum('S', 'U', 'F', name='urgencytype'), nullable=True),
    sa.Column('container_count_actual', sa.Integer(), nullable=True),
    sa.Column('fixation', sa.Enum('NBF_10', 'OSMIUM', 'BOUIN', 'ALCOHOL', 'GLUTARALDEHYDE_2', 'OTHER', name='fixationtype'), nullable=True),
    sa.Column('macro_description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_table('devices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['serial_number'], ['manufactured_devices.serial_number'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.cor_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)
    op.create_index(op.f('ix_devices_token'), 'devices', ['token'], unique=True)
    op.create_table('doctors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('work_email', sa.String(length=250), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('doctors_photo', sa.LargeBinary(), nullable=True),
    sa.Column('scientific_degree', sa.String(length=100), nullable=True),
    sa.Column('date_of_last_attestation', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'agreed', 'rejected', 'need_revision', name='doctor_status'), nullable=False),
    sa.Column('passport_code', sa.String(length=20), nullable=True),
    sa.Column('taxpayer_identification_number', sa.String(length=20), nullable=True),
    sa.Column('reserv_scan_data', sa.LargeBinary(), nullable=True),
    sa.Column('reserv_scan_file_type', sa.String(), nullable=True),
    sa.Column('date_of_next_review', sa.Date(), nullable=True),
    sa.Column('place_of_registration', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.cor_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doctor_id'),
    sa.UniqueConstraint('work_email')
    )
    op.create_table('energy_managers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('energy_manager_cor_id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('surname', sa.String(length=100), nullable=True),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('lab_assistants_photo', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['energy_manager_cor_id'], ['users.cor_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('energy_manager_cor_id')
    )
    op.create_table('lab_assistants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lab_assistant_cor_id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('surname', sa.String(length=100), nullable=True),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('lab_assistants_photo', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['lab_assistant_cor_id'], ['users.cor_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lab_assistant_cor_id')
    )
    op.create_table('otp_records',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('record_name', sa.String(length=250), nullable=False),
    sa.Column('username', sa.String(length=250), nullable=True),
    sa.Column('private_key', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('edited_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_index('idx_otp_records_user_id', 'otp_records', ['user_id'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_cor_id', sa.String(length=36), nullable=False),
    sa.Column('encrypted_surname', sa.LargeBinary(), nullable=True),
    sa.Column('encrypted_first_name', sa.LargeBinary(), nullable=True),
    sa.Column('encrypted_middle_name', sa.LargeBinary(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=250), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('photo', sa.LargeBinary(), nullable=True),
    sa.Column('change_date', sa.DateTime(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_cor_id'], ['users.cor_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_cor_id')
    )
    op.create_table('profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('encrypted_surname', sa.LargeBinary(), nullable=True),
    sa.Column('encrypted_first_name', sa.LargeBinary(), nullable=True),
    sa.Column('encrypted_middle_name', sa.LargeBinary(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('car_brand', sa.String(length=100), nullable=True),
    sa.Column('engine_type', sa.String(length=50), nullable=True),
    sa.Column('fuel_tank_volume', sa.Integer(), nullable=True),
    sa.Column('photo_data', sa.LargeBinary(), nullable=True),
    sa.Column('photo_file_type', sa.String(), nullable=True),
    sa.Column('change_date', sa.DateTime(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('records',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('record_name', sa.String(length=250), nullable=False),
    sa.Column('website', sa.String(length=250), nullable=True),
    sa.Column('username', sa.LargeBinary(), nullable=True),
    sa.Column('password', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('edited_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_index('idx_records_user_id', 'records', ['user_id'], unique=False)
    op.create_table('referrals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False, comment='ID связанного кейса'),
    sa.Column('case_number', sa.String(), nullable=False, comment='Номер кейса'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='Дата создания направления'),
    sa.Column('research_type', sa.Enum('CYTOLOGY', 'HISTOPATHOLOGY', 'IMMUNOHISTOCHEMISTRY', 'FISH_CISH', name='studytype'), nullable=True, comment='Вид исследования'),
    sa.Column('container_count', sa.Integer(), nullable=True, comment='Фактическое количество контейнеров'),
    sa.Column('medical_card_number', sa.String(), nullable=True, comment='Номер медкарты'),
    sa.Column('clinical_data', sa.Text(), nullable=True, comment='Клинические данные'),
    sa.Column('clinical_diagnosis', sa.String(), nullable=True, comment='Клинический диагноз'),
    sa.Column('medical_institution', sa.String(), nullable=True, comment='Медицинское учреждение'),
    sa.Column('department', sa.String(), nullable=True, comment='Отделение'),
    sa.Column('attending_doctor', sa.String(), nullable=True, comment='Лечащий врач'),
    sa.Column('doctor_contacts', sa.String(), nullable=True, comment='Контакты врача'),
    sa.Column('medical_procedure', sa.String(), nullable=True, comment='Медицинская процедура'),
    sa.Column('final_report_delivery', sa.Text(), nullable=True, comment='Финальный репорт отправить'),
    sa.Column('issued_at', sa.DateTime(), nullable=True, comment='Выдано (дата)'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_index(op.f('ix_referrals_case_number'), 'referrals', ['case_number'], unique=False)
    op.create_index(op.f('ix_referrals_id'), 'referrals', ['id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('immunohistochemical_profile', sa.Text(), nullable=True),
    sa.Column('molecular_genetic_profile', sa.Text(), nullable=True),
    sa.Column('pathomorphological_diagnosis', sa.Text(), nullable=True),
    sa.Column('icd_code', sa.String(length=50), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('attached_glass_ids', sa.ARRAY(sa.String(length=36)), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_table('samples',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('sample_number', sa.String(length=50), nullable=True),
    sa.Column('cassette_count', sa.Integer(), nullable=True),
    sa.Column('glass_count', sa.Integer(), nullable=True),
    sa.Column('archive', sa.Boolean(), nullable=True),
    sa.Column('macro_description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('device_type', sa.String(length=250), nullable=True),
    sa.Column('device_info', sa.String(length=250), nullable=True),
    sa.Column('ip_address', sa.String(length=250), nullable=True),
    sa.Column('device_os', sa.String(length=250), nullable=True),
    sa.Column('jti', sa.String(), nullable=True, comment='JTI последнего Access токена, выданного для этой сессии'),
    sa.Column('refresh_token', sa.LargeBinary(), nullable=True),
    sa.Column('access_token', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.cor_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti')
    )
    op.create_index('idx_user_sessions_user_id', 'user_sessions', ['user_id'], unique=False)
    op.create_table('user_settings',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('local_password_storage', sa.Boolean(), nullable=True),
    sa.Column('cloud_password_storage', sa.Boolean(), nullable=True),
    sa.Column('local_medical_storage', sa.Boolean(), nullable=True),
    sa.Column('cloud_medical_storage', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('cassettes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sample_id', sa.String(length=36), nullable=False),
    sa.Column('cassette_number', sa.String(length=50), nullable=True),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('glass_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('certificates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('file_data', sa.LargeBinary(), nullable=True),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('series', sa.String(length=50), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('university', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.doctor_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clinic_affiliations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('clinic_name', sa.String(length=250), nullable=False),
    sa.Column('department', sa.String(length=250), nullable=True),
    sa.Column('position', sa.String(length=250), nullable=True),
    sa.Column('specialty', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.doctor_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clinic_patient_statuses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('patient_status_for_clinic', sa.Enum('registered', 'diagnosed', 'under_treatment', 'hospitalized', 'discharged', 'died', 'in_process', 'referred_for_additional_consultation', 'awaiting_report', 'completed', 'error', name='patientclinicstatus'), nullable=True),
    sa.Column('assigned_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_access',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('granting_user_id', sa.String(), nullable=True),
    sa.Column('accessing_user_id', sa.String(), nullable=True),
    sa.Column('access_level', sa.Enum('READ', 'READ_WRITE', 'SHARE', name='accesslevel'), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['accessing_user_id'], ['users.cor_id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['granting_user_id'], ['users.cor_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_access_id'), 'device_access', ['id'], unique=False)
    op.create_table('diplomas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('file_data', sa.LargeBinary(), nullable=True),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('series', sa.String(length=50), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('university', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.doctor_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doctor_patient_statuses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('registered', 'diagnosed', 'under_treatment', 'hospitalized', 'discharged', 'died', 'in_process', 'referred_for_additional_consultation', name='patientstatus'), nullable=False),
    sa.Column('assigned_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'doctor_id', name='unique_patient_doctor_status')
    )
    op.create_table('doctor_signatures',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('signature_name', sa.String(length=255), nullable=True),
    sa.Column('signature_scan_data', sa.LargeBinary(), nullable=True),
    sa.Column('signature_scan_type', sa.String(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('records_tags',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['records.record_id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('record_id', 'tag_id')
    )
    op.create_table('referral_attachments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('referral_id', sa.String(), nullable=False, comment='ID связанного направления'),
    sa.Column('filename', sa.String(), nullable=False, comment='Имя файла'),
    sa.Column('content_type', sa.String(), nullable=False, comment='Тип содержимого (например, image/jpeg, application/pdf)'),
    sa.Column('file_data', sa.LargeBinary(), nullable=False, comment='Бинарные данные файла'),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referral_attachments_id'), 'referral_attachments', ['id'], unique=False)
    op.create_table('glasses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cassette_id', sa.String(length=36), nullable=False),
    sa.Column('glass_number', sa.Integer(), nullable=True),
    sa.Column('staining', sa.Enum('HE', 'ALCIAN_PAS', 'CONGO_RED', 'MASSON_TRICHROME', 'VAN_GIESON', 'ZIEHL_NEELSEN', 'WARTHIN_STARRY_SILVER', 'GROCOTT_METHENAMINE_SILVER', 'TOLUIDINE_BLUE', 'PERLS_PRUSSIAN_BLUE', 'PAMS', 'PICROSIRIUS', 'SIRIUS_RED', 'THIOFLAVIN_T', 'TRICHROME_AFOG', 'VON_KOSSA', 'GIEMSA', 'OTHAR', name='stainingtype'), nullable=True),
    sa.Column('glass_data', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['cassette_id'], ['cassettes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_signatures',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('doctor_signature_id', sa.String(length=36), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['doctor_signature_id'], ['doctor_signatures.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_signatures')
    op.drop_table('glasses')
    op.drop_index(op.f('ix_referral_attachments_id'), table_name='referral_attachments')
    op.drop_table('referral_attachments')
    op.drop_table('records_tags')
    op.drop_table('doctor_signatures')
    op.drop_table('doctor_patient_statuses')
    op.drop_table('diplomas')
    op.drop_index(op.f('ix_device_access_id'), table_name='device_access')
    op.drop_table('device_access')
    op.drop_table('clinic_patient_statuses')
    op.drop_table('clinic_affiliations')
    op.drop_table('certificates')
    op.drop_table('cassettes')
    op.drop_table('user_settings')
    op.drop_index('idx_user_sessions_user_id', table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_table('samples')
    op.drop_table('reports')
    op.drop_index(op.f('ix_referrals_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_case_number'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_index('idx_records_user_id', table_name='records')
    op.drop_table('records')
    op.drop_table('profiles')
    op.drop_table('patients')
    op.drop_index('idx_otp_records_user_id', table_name='otp_records')
    op.drop_table('otp_records')
    op.drop_table('lab_assistants')
    op.drop_table('energy_managers')
    op.drop_table('doctors')
    op.drop_index(op.f('ix_devices_token'), table_name='devices')
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_table('case_parameters')
    op.drop_index('idx_verification_email', table_name='verification')
    op.drop_table('verification')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_cor_id', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_tags_name', table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_printing_device_id'), table_name='printing_device')
    op.drop_table('printing_device')
    op.drop_index(op.f('ix_manufactured_devices_token'), table_name='manufactured_devices')
    op.drop_index(op.f('ix_manufactured_devices_id'), table_name='manufactured_devices')
    op.drop_table('manufactured_devices')
    op.drop_index(op.f('ix_cor_id_auth_sessions_session_token'), table_name='cor_id_auth_sessions')
    op.drop_index(op.f('ix_cor_id_auth_sessions_email'), table_name='cor_id_auth_sessions')
    op.drop_index(op.f('ix_cor_id_auth_sessions_cor_id'), table_name='cor_id_auth_sessions')
    op.drop_index('idx_cor_id_auth_sessions_token', table_name='cor_id_auth_sessions')
    op.drop_table('cor_id_auth_sessions')
    op.drop_index(op.f('ix_cases_patient_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_case_code'), table_name='cases')
    op.drop_table('cases')
    # ### end Alembic commands ###
