"""add lawyer column v1.0.2

Revision ID: 3cf73d91cbf4
Revises: 1b3b51eb648d
Create Date: 2025-06-17 11:19:58.885676

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3cf73d91cbf4"
down_revision: Union[str, None] = "1b3b51eb648d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lawyers",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("lawyer_cor_id", sa.String(length=36), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=True),
        sa.Column("surname", sa.String(length=100), nullable=True),
        sa.Column("middle_name", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["lawyer_cor_id"],
            ["users.cor_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("lawyer_cor_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("lawyers")
    # ### end Alembic commands ###
