"""update DoctorSignatureSession table  v1.1.22

Revision ID: 3fac354260f0
Revises: 3494ffbd8c8b
Create Date: 2025-10-09 12:17:01.562648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fac354260f0'
down_revision: Union[str, None] = '3494ffbd8c8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_signature_sessions', sa.Column('ophthalmological_prescription_id', sa.String(length=36), nullable=True))
    op.alter_column('doctor_signature_sessions', 'diagnosis_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('doctor_signature_sessions', 'diagnosis_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_column('doctor_signature_sessions', 'ophthalmological_prescription_id')
    # ### end Alembic commands ###
