"""case code unique true  v1.0.0.38

Revision ID: 44e1e9496450
Revises: 9fa8269ec029
Create Date: 2025-06-04 12:42:44.999181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44e1e9496450'
down_revision: Union[str, None] = '9fa8269ec029'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cases_case_code', table_name='cases')
    op.create_index(op.f('ix_cases_case_code'), 'cases', ['case_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cases_case_code'), table_name='cases')
    op.create_index('ix_cases_case_code', 'cases', ['case_code'], unique=False)
    # ### end Alembic commands ###
