"""fix2 glass model v1.0.0.15

Revision ID: 45b6f9d1fe32
Revises: 4f22c2699b4a
Create Date: 2025-04-28 12:26:26.741418

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "45b6f9d1fe32"
down_revision: Union[str, None] = "4f22c2699b4a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
