"""add symptomatically to MedicineSchedule  v1.1.19

Revision ID: 4a0a13100f2f
Revises: df31f77e41ed
Create Date: 2025-10-08 14:28:02.814622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a0a13100f2f'
down_revision: Union[str, None] = 'df31f77e41ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicine_schedules', sa.Column('symptomatically', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medicine_schedules', 'symptomatically')
    # ### end Alembic commands ###
