"""fix glass model v1.0.0.14

Revision ID: 4f22c2699b4a
Revises: dd96fb775891
Create Date: 2025-04-28 12:24:16.168142

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4f22c2699b4a"
down_revision: Union[str, None] = "dd96fb775891"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
