"""update doctor  models  v1.0.0.23

Revision ID: 5055df5b5936
Revises: 0acd5a1b4a9e
Create Date: 2025-05-09 11:53:23.881024

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5055df5b5936"
down_revision: Union[str, None] = "0acd5a1b4a9e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "doctors", sa.Column("passport_code", sa.String(length=20), nullable=True)
    )
    op.add_column(
        "doctors",
        sa.Column(
            "taxpayer_identification_number", sa.String(length=20), nullable=True
        ),
    )
    op.add_column("doctors", sa.Column("reserv_scan", sa.LargeBinary(), nullable=True))
    op.add_column("doctors", sa.Column("date_of_next_review", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("doctors", "date_of_next_review")
    op.drop_column("doctors", "reserv_scan")
    op.drop_column("doctors", "taxpayer_identification_number")
    op.drop_column("doctors", "passport_code")
    # ### end Alembic commands ###
