"""add case_owner column v1.0.6

Revision ID: 5a87ae883a42
Revises: 28a3a23353f5
Create Date: 2025-06-23 11:52:50.238121

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5a87ae883a42"
down_revision: Union[str, None] = "28a3a23353f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cases", sa.Column("case_owner", sa.String(length=36), nullable=True))
    op.create_foreign_key(None, "cases", "doctors", ["case_owner"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "cases", type_="foreignkey")
    op.drop_column("cases", "case_owner")
    # ### end Alembic commands ###
