"""add token to session  v1.0.0.39

Revision ID: 5c4458302efb
Revises: 44e1e9496450
Create Date: 2025-06-05 14:28:10.641211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c4458302efb'
down_revision: Union[str, None] = '44e1e9496450'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sessions', sa.Column('access_token', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_sessions', 'access_token')
    # ### end Alembic commands ###
