"""Fix doctor documents  model v1.0.0.5

Revision ID: 63aebf60cf27
Revises: d0bfa451c8d8
Create Date: 2025-03-21 09:48:19.900176

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "63aebf60cf27"
down_revision: Union[str, None] = "d0bfa451c8d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "doctors", ["doctor_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "doctors", type_="unique")
    # ### end Alembic commands ###
