"""add acc create time

Revision ID: 63c1b26ff55b
Revises: 7ed54c411e14
Create Date: 2024-11-01 13:52:28.667368

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import func

# revision identifiers, used by Alembic.
revision: str = "63c1b26ff55b"
down_revision: Union[str, None] = "7ed54c411e14"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "created_at", sa.DateTime(), nullable=False, server_default=func.now()
        ),
    )

    # Обновите существующие записи, чтобы установить значение для 'created_at'
    connection = op.get_bind()
    connection.execute(
        sa.text("UPDATE users SET created_at = NOW() WHERE created_at IS NULL")
    )

    op.alter_column("users", "created_at", nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "created_at")
    # ### end Alembic commands ###
