"""add doctor phone number v1.0.0.8

Revision ID: 67f06d1450ba
Revises: 992b8774c0ae
Create Date: 2025-04-10 11:36:33.360619

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "67f06d1450ba"
down_revision: Union[str, None] = "992b8774c0ae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "doctors", sa.Column("phone_number", sa.String(length=20), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("doctors", "phone_number")
    # ### end Alembic commands ###
