"""add jti to UserSession  v1.0.0.35

Revision ID: 68e9e50e0cf3
Revises: f18ee07d4632
Create Date: 2025-05-27 13:07:59.182083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68e9e50e0cf3'
down_revision: Union[str, None] = 'f18ee07d4632'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sessions', sa.Column('jti', sa.String(), nullable=True, comment='JTI последнего Access токена, выданного для этой сессии'))
    op.create_unique_constraint(None, 'user_sessions', ['jti'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_sessions', type_='unique')
    op.drop_column('user_sessions', 'jti')
    # ### end Alembic commands ###
