"""add printing device  v1.0.0.30

Revision ID: 6b3808f33492
Revises: 057d93d335dd
Create Date: 2025-05-16 10:10:37.101448

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6b3808f33492"
down_revision: Union[str, None] = "057d93d335dd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "printing_device",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("device_class", sa.String(), nullable=False),
        sa.Column("device_identifier", sa.String(), nullable=False),
        sa.Column("subnet_mask", sa.String(), nullable=True),
        sa.Column("gateway", sa.String(), nullable=True),
        sa.Column("ip_address", sa.String(), nullable=False),
        sa.Column("port", sa.Integer(), nullable=True),
        sa.Column("comment", sa.String(), nullable=True),
        sa.Column("location", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_identifier"),
    )
    op.create_index(
        op.f("ix_printing_device_id"), "printing_device", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_printing_device_id"), table_name="printing_device")
    op.drop_table("printing_device")
    # ### end Alembic commands ###
