"""Fix doctor model v1.0.0.3

Revision ID: 71439ce40939
Revises: 8f5b8cf601ec
Create Date: 2025-03-20 13:58:13.814308

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "71439ce40939"
down_revision: Union[str, None] = "8f5b8cf601ec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
