"""add case general macrodescription, microdescription, conclusion  v1.0.0.39

Revision ID: 7777cdb243ab
Revises: 5c4458302efb
Create Date: 2025-06-06 15:12:41.830590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7777cdb243ab'
down_revision: Union[str, None] = '5c4458302efb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('pathohistological_conclusion', sa.Text(), nullable=True))
    op.add_column('cases', sa.Column('microdescription', sa.Text(), nullable=True))
    op.add_column('cases', sa.Column('general_macrodescription', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'general_macrodescription')
    op.drop_column('cases', 'microdescription')
    op.drop_column('cases', 'pathohistological_conclusion')
    # ### end Alembic commands ###
