"""Added UserSession column ip_address

Revision ID: 77be80ad184f
Revises: 4a44dbd4c364
Create Date: 2025-03-07 14:53:48.994947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77be80ad184f'
down_revision: Union[str, None] = '4a44dbd4c364'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sessions', sa.Column('ip_address', sa.String(length=250), nullable=True))
    op.drop_column('user_sessions', 'ip_adress')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sessions', sa.Column('ip_adress', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.drop_column('user_sessions', 'ip_address')
    # ### end Alembic commands ###
