"""add patient and patient_doctor table v1.0.0.9

Revision ID: 7849fbaaefd2
Revises: 67f06d1450ba
Create Date: 2025-04-15 12:23:43.584634

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7849fbaaefd2"
down_revision: Union[str, None] = "67f06d1450ba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "patients",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("patient_cor_id", sa.String(length=36), nullable=False),
        sa.Column("encrypted_surname", sa.LargeBinary(), nullable=True),
        sa.Column("encrypted_first_name", sa.LargeBinary(), nullable=True),
        sa.Column("encrypted_middle_name", sa.LargeBinary(), nullable=True),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("sex", sa.String(length=10), nullable=True),
        sa.Column("email", sa.String(length=250), nullable=True),
        sa.Column("phone_number", sa.String(length=20), nullable=True),
        sa.Column("address", sa.String(length=500), nullable=True),
        sa.Column("photo", sa.LargeBinary(), nullable=True),
        sa.Column("change_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["patient_cor_id"],
            ["users.cor_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("patient_cor_id"),
    )
    op.create_table(
        "doctor_patient_statuses",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("doctor_id", sa.String(length=36), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "registered", "under_treatment", "discharged", name="patientstatus"
            ),
            nullable=False,
        ),
        sa.Column("assigned_date", sa.DateTime(), nullable=True),
        sa.Column("updated_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["doctor_id"],
            ["doctors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "patient_id", "doctor_id", name="unique_patient_doctor_status"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("doctor_patient_statuses")
    op.drop_table("patients")
    # ### end Alembic commands ###
