"""add charge_battery_value  v1.1.5

Revision ID: 7a07fa844f6d
Revises: 8144e10fcfec
Create Date: 2025-07-17 11:45:32.650749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a07fa844f6d'
down_revision: Union[str, None] = '8144e10fcfec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'energetic_schedule', 
        sa.Column('charge_battery_value', sa.Integer(), nullable=True, server_default=sa.text('300'), comment='заряжать батарею в этом режиме с каким то током')
    )
    
    op.execute(sa.text("UPDATE energetic_schedule SET charge_battery_value = 300 WHERE charge_battery_value IS NULL"))
    op.alter_column(
        'energetic_schedule', 
        'charge_battery_value', 
        existing_type=sa.Integer(), 
        nullable=False, 
        existing_server_default=sa.text('300') 
    )
    op.drop_column('energetic_schedule', 'charge_battery')
    op.alter_column('patients', 'search_tokens',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'search_tokens',
                    existing_type=sa.TEXT(),
                    nullable=True,
                    existing_server_default=sa.text("''::text"))
    op.add_column('energetic_schedule', sa.Column('charge_battery', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Флаг: заряжать батарею в этом режиме'))
    op.drop_column('energetic_schedule', 'charge_battery_value')
    # ### end Alembic commands ###
