"""add UniqueConstraint('user_id', 'device_info') v1.1.3

Revision ID: 7d8bc673e1b2
Revises: 899405bd0824
Create Date: 2025-07-11 13:40:36.194337

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7d8bc673e1b2"
down_revision: Union[str, None] = "899405bd0824"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_user_device_session", "user_sessions", ["user_id", "device_info"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_user_device_session", "user_sessions", type_="unique")
    # ### end Alembic commands ###
