"""add energetic shedule table v1.1.1

Revision ID: 899405bd0824
Revises: 91f3353a1fd6
Create Date: 2025-07-10 11:20:21.684951

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "899405bd0824"
down_revision: Union[str, None] = "91f3353a1fd6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "energetic_schedule",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "start_time",
            sa.Time(),
            nullable=False,
            comment="Время начала работы режима (ЧЧ:ММ)",
        ),
        sa.Column(
            "duration",
            sa.Interval(),
            nullable=False,
            comment="Продолжительность режима (например, 2 часа 30 минут)",
        ),
        sa.Column(
            "end_time",
            sa.Time(),
            nullable=False,
            comment="Время окончания работы режима (ЧЧ:ММ)",
        ),
        sa.Column(
            "grid_feed_w",
            sa.Integer(),
            nullable=False,
            comment="Параметр отдачи в сеть (Вт)",
        ),
        sa.Column(
            "battery_level_percent",
            sa.Integer(),
            nullable=False,
            comment="Целевой уровень батареи (%)",
        ),
        sa.Column(
            "charge_battery",
            sa.Boolean(),
            nullable=False,
            comment="Флаг: заряжать батарею в этом режиме",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            comment="Флаг: активно ли это расписание",
        ),
        sa.Column(
            "is_manual_mode",
            sa.Boolean(),
            nullable=False,
            comment="Флаг: находится ли инвертор в ручном режиме",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("energetic_schedule")
    # ### end Alembic commands ###
