"""update usersession  v1.1.13

Revision ID: 899911e55197
Revises: c9476e916783
Create Date: 2025-08-21 12:09:11.708623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '899911e55197'
down_revision: Union[str, None] = 'c9476e916783'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_app_device_session', 'user_sessions', type_='unique')
    op.drop_constraint('uq_user_device_session_legacy', 'user_sessions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_device_session_legacy', 'user_sessions', ['user_id', 'device_info'])
    op.create_unique_constraint('uq_user_app_device_session', 'user_sessions', ['user_id', 'app_id', 'device_id'])
    # ### end Alembic commands ###
