"""add report macrodescription v1.0.3

Revision ID: 8b5cb96646d2
Revises: 3cf73d91cbf4
Create Date: 2025-06-23 09:44:48.108588

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8b5cb96646d2"
down_revision: Union[str, None] = "3cf73d91cbf4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reports", sa.Column("report_macrodescription", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reports", "report_macrodescription")
    # ### end Alembic commands ###
