"""Fix doctor model v1.0.0.2

Revision ID: 8f5b8cf601ec
Revises: ada9cdc5dd88
Create Date: 2025-03-20 13:54:36.763205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f5b8cf601ec'
down_revision: Union[str, None] = 'ada9cdc5dd88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
