"""add pbm table v1.0.9

Revision ID: 987ff91460bb
Revises: cecef02c98dc
Create Date: 2025-06-25 16:22:04.432172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '987ff91460bb'
down_revision: Union[str, None] = 'cecef02c98dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blood_pressure_measurements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('systolic_pressure', sa.Integer(), nullable=False, comment='Систолическое (верхнее) артериальное давление'),
    sa.Column('diastolic_pressure', sa.Integer(), nullable=False, comment='Диастолическое (нижнее) артериальное давление'),
    sa.Column('pulse', sa.Integer(), nullable=False, comment='Частота сердечных сокращений (пульс)'),
    sa.Column('measured_at', sa.DateTime(), nullable=False, comment='Дата и время измерения, полученное с устройства'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Дата и время сохранения записи в БД'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bpm_measured_at', 'blood_pressure_measurements', ['measured_at'], unique=False)
    op.create_index('idx_bpm_user_id', 'blood_pressure_measurements', ['user_id'], unique=False)
    op.create_index(op.f('ix_blood_pressure_measurements_user_id'), 'blood_pressure_measurements', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blood_pressure_measurements_user_id'), table_name='blood_pressure_measurements')
    op.drop_index('idx_bpm_user_id', table_name='blood_pressure_measurements')
    op.drop_index('idx_bpm_measured_at', table_name='blood_pressure_measurements')
    op.drop_table('blood_pressure_measurements')
    # ### end Alembic commands ###
