"""add auth session model v1.0.0.7

Revision ID: 992b8774c0ae
Revises: 1c9da8339f0e
Create Date: 2025-04-08 14:08:54.341116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '992b8774c0ae'
down_revision: Union[str, None] = '1c9da8339f0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cor_id_auth_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('cor_id', sa.String(length=250), nullable=True),
    sa.Column('session_token', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'TIMEOUT', name='authsessionstatus'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cor_id_auth_sessions_token', 'cor_id_auth_sessions', ['session_token'], unique=False)
    op.create_index(op.f('ix_cor_id_auth_sessions_cor_id'), 'cor_id_auth_sessions', ['cor_id'], unique=False)
    op.create_index(op.f('ix_cor_id_auth_sessions_email'), 'cor_id_auth_sessions', ['email'], unique=False)
    op.create_index(op.f('ix_cor_id_auth_sessions_session_token'), 'cor_id_auth_sessions', ['session_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cor_id_auth_sessions_session_token'), table_name='cor_id_auth_sessions')
    op.drop_index(op.f('ix_cor_id_auth_sessions_email'), table_name='cor_id_auth_sessions')
    op.drop_index(op.f('ix_cor_id_auth_sessions_cor_id'), table_name='cor_id_auth_sessions')
    op.drop_index('idx_cor_id_auth_sessions_token', table_name='cor_id_auth_sessions')
    op.drop_table('cor_id_auth_sessions')
    # ### end Alembic commands ###
