"""Added UserSession and db indexes_fixed

Revision ID: 9ab539bdaedb
Revises: 5dd388ebe8f1
Create Date: 2025-03-06 13:47:11.924436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ab539bdaedb'
down_revision: Union[str, None] = '5dd388ebe8f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_otp_records_user_id', 'otp_records', ['user_id'], unique=False)
    op.create_index('idx_records_user_id', 'records', ['user_id'], unique=False)
    op.create_index('idx_tags_name', 'tags', ['name'], unique=False)
    op.create_index('idx_user_sessions_user_id', 'user_sessions', ['user_id'], unique=False)
    op.drop_constraint('users_backup_email_key', 'users', type_='unique')
    op.create_index('idx_users_cor_id', 'users', ['cor_id'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_verification_email', 'verification', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_verification_email', table_name='verification')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_cor_id', table_name='users')
    op.create_unique_constraint('users_backup_email_key', 'users', ['backup_email'])
    op.drop_index('idx_user_sessions_user_id', table_name='user_sessions')
    op.drop_index('idx_tags_name', table_name='tags')
    op.drop_index('idx_records_user_id', table_name='records')
    op.drop_index('idx_otp_records_user_id', table_name='otp_records')
    # ### end Alembic commands ###
