"""change patient status  v1.0.0.37

Revision ID: 9fa8269ec029
Revises: b7f9671da81b
Create Date: 2025-06-03 13:57:21.476910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fa8269ec029'
down_revision: Union[str, None] = 'b7f9671da81b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


old_enum_name = 'patientstatus' 

old_status_values = (
    'registered',
    'under_treatment',
    'discharged',
)


new_status_values = (
    'registered',
    'diagnosed', 
    'under_treatment',
    'hospitalized', 
    'discharged',
    'died', 
    'in_process', 
    'referred_for_additional_consultation', 
)

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for value in new_status_values:
        if value not in old_status_values:
            op.execute(f"ALTER TYPE {old_enum_name} ADD VALUE '{value}'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(f"ALTER TYPE {old_enum_name} DROP VALUE 'referred_for_additional_consultation'")
    op.execute(f"ALTER TYPE {old_enum_name} DROP VALUE 'in_process'")
    op.execute(f"ALTER TYPE {old_enum_name} DROP VALUE 'died'")
    op.execute(f"ALTER TYPE {old_enum_name} DROP VALUE 'hospitalized'")
    op.execute(f"ALTER TYPE {old_enum_name} DROP VALUE 'diagnosed'")
    # ### end Alembic commands ###
