"""update case models to delete function v1.0.0.16

Revision ID: 9fe4ae4b3fec
Revises: 45b6f9d1fe32
Create Date: 2025-04-28 13:44:45.980143

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9fe4ae4b3fec"
down_revision: Union[str, None] = "45b6f9d1fe32"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
