"""add cerbo table v1.0.11

Revision ID: a2da3b6c7aa5
Revises: 9431ea1024c7
Create Date: 2025-07-02 16:34:47.396656

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a2da3b6c7aa5"
down_revision: Union[str, None] = "9431ea1024c7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cerbo_measurements",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
            comment="Дата и время сохранения записи в БД",
        ),
        sa.Column(
            "measured_at",
            sa.DateTime(),
            nullable=False,
            comment="Дата и время измерения, полученное с устройства",
        ),
        sa.Column("object_name", sa.String(), nullable=True),
        sa.Column("general_battery_power", sa.Float(), nullable=False),
        sa.Column("inverter_total_ac_output", sa.Float(), nullable=False),
        sa.Column("ess_total_input_power", sa.Float(), nullable=False),
        sa.Column("solar_total_pv_power", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cerbo_measurements_object_name"),
        "cerbo_measurements",
        ["object_name"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_cerbo_measurements_object_name"), table_name="cerbo_measurements"
    )
    op.drop_table("cerbo_measurements")
    # ### end Alembic commands ###
