"""update corid auth session model  v1.1.14

Revision ID: a3294d709180
Revises: 899911e55197
Create Date: 2025-08-21 13:24:35.229911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3294d709180'
down_revision: Union[str, None] = '899911e55197'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cor_id_auth_sessions', sa.Column('app_id', sa.String(length=250), nullable=True))
    op.add_column('cor_id_auth_sessions', sa.Column('device_id', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cor_id_auth_sessions', 'device_id')
    op.drop_column('cor_id_auth_sessions', 'app_id')
    # ### end Alembic commands ###
