"""set default False for new boolean columns (is printed glasses, cassetes, qr) v1.0.15

Revision ID: a6570481e591
Revises: 37567c675f11
Create Date: 2025-07-08 10:30:55.990881

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a6570481e591"
down_revision: Union[str, None] = "37567c675f11"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    op.execute(
        sa.text(
            """
            UPDATE cases
            SET is_printed_cassette = FALSE
            WHERE is_printed_cassette IS NULL;
        """
        )
    )

    op.execute(
        sa.text(
            """
            UPDATE cases
            SET is_printed_glass = FALSE
            WHERE is_printed_glass IS NULL;
        """
        )
    )

    op.execute(
        sa.text(
            """
            UPDATE cases
            SET is_printed_qr = FALSE
            WHERE is_printed_qr IS NULL;
        """
        )
    )

    op.execute(
        sa.text(
            """
            UPDATE samples
            SET is_printed_cassette = FALSE
            WHERE is_printed_cassette IS NULL;
        """
        )
    )

    op.execute(
        sa.text(
            """
            UPDATE samples
            SET is_printed_glass = FALSE
            WHERE is_printed_glass IS NULL;
        """
        )
    )

    op.execute(
        sa.text(
            """
            UPDATE cassettes
            SET is_printed = FALSE
            WHERE is_printed IS NULL;
        """
        )
    )

    op.execute(
        sa.text(
            """
            UPDATE glasses
            SET is_printed = FALSE
            WHERE is_printed IS NULL;
        """
        )
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
