"""Added doctors models

Revision ID: ada9cdc5dd88
Revises: 8ad8a66e89d1
Create Date: 2025-03-20 13:25:22.762930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ada9cdc5dd88'
down_revision: Union[str, None] = '8ad8a66e89d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('work_email', sa.String(length=250), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('surname', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('doctors_photo', sa.LargeBinary(), nullable=True),
    sa.Column('scientific_degree', sa.String(length=100), nullable=True),
    sa.Column('date_of_last_attestation', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', name='doctorstatus'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.cor_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_email')
    )
    op.create_table('certificates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('scan', sa.LargeBinary(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('series', sa.String(length=50), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('university', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clinic_affiliations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('clinic_name', sa.String(length=250), nullable=False),
    sa.Column('department', sa.String(length=250), nullable=True),
    sa.Column('position', sa.String(length=250), nullable=True),
    sa.Column('specialty', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diplomas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('scan', sa.LargeBinary(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('series', sa.String(length=50), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('university', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_otp_records_user_id', 'otp_records', ['user_id'], unique=False)
    op.create_index('idx_records_user_id', 'records', ['user_id'], unique=False)
    op.create_foreign_key(None, 'records', 'users', ['user_id'], ['id'])
    op.create_index('idx_tags_name', 'tags', ['name'], unique=False)
    op.create_foreign_key(None, 'user_settings', 'users', ['user_id'], ['id'])
    op.create_index('idx_verification_email', 'verification', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_verification_email', table_name='verification')
    op.drop_constraint(None, 'user_settings', type_='foreignkey')
    op.drop_index('idx_tags_name', table_name='tags')
    op.drop_constraint(None, 'records', type_='foreignkey')
    op.drop_index('idx_records_user_id', table_name='records')
    op.drop_index('idx_otp_records_user_id', table_name='otp_records')
    op.drop_table('diplomas')
    op.drop_table('clinic_affiliations')
    op.drop_table('certificates')
    op.drop_table('doctors')
    # ### end Alembic commands ###
