"""add doctor signature session  v1.1.10

Revision ID: ae521c869e08
Revises: 00b73b2e1010
Create Date: 2025-08-15 11:20:47.444005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae521c869e08'
down_revision: Union[str, None] = '00b73b2e1010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_signature_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_token', sa.String(), nullable=False),
    sa.Column('doctor_cor_id', sa.String(length=36), nullable=False),
    sa.Column('diagnosis_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_token')
    )
    op.execute("ALTER TYPE grossing_status ADD VALUE 'IN_SIGNING_STATUS'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doctor_signature_sessions')
    op.execute(
        "ALTER TYPE grossing_status DROP VALUE 'IN_SIGNING_STATUS'"
    )  
    # ### end Alembic commands ###
