"""add sample macrodescription  v1.0.0.32

Revision ID: af7b7620f0e6
Revises: f92115dc9c34
Create Date: 2025-05-21 14:35:18.498537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af7b7620f0e6'
down_revision: Union[str, None] = 'f92115dc9c34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('samples', sa.Column('macro_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('samples', 'macro_description')
    # ### end Alembic commands ###
