"""add profile table  v1.0.0.36

Revision ID: b7f9671da81b
Revises: 68e9e50e0cf3
Create Date: 2025-06-02 11:10:40.961892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7f9671da81b'
down_revision: Union[str, None] = '68e9e50e0cf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('encrypted_surname', sa.LargeBinary(), nullable=True),
    sa.Column('encrypted_first_name', sa.LargeBinary(), nullable=True),
    sa.Column('encrypted_middle_name', sa.LargeBinary(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('car_brand', sa.String(length=100), nullable=True),
    sa.Column('engine_type', sa.String(length=50), nullable=True),
    sa.Column('fuel_tank_volume', sa.Integer(), nullable=True),
    sa.Column('photo_data', sa.LargeBinary(), nullable=True),
    sa.Column('photo_file_type', sa.String(), nullable=True),
    sa.Column('change_date', sa.DateTime(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profiles')
    # ### end Alembic commands ###
