"""add doctor_diagnosis table v1.0.4

Revision ID: be97999f4c62
Revises: 8b5cb96646d2
Create Date: 2025-06-23 10:48:29.146986

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "be97999f4c62"
down_revision: Union[str, None] = "8b5cb96646d2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "doctor_diagnoses",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("report_id", sa.String(length=36), nullable=False),
        sa.Column("doctor_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("immunohistochemical_profile", sa.Text(), nullable=True),
        sa.Column("molecular_genetic_profile", sa.Text(), nullable=True),
        sa.Column("pathomorphological_diagnosis", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["doctor_id"],
            ["doctors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["reports.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "report_signatures",
        sa.Column("diagnosis_entry_id", sa.String(length=36), nullable=True),
    )
    op.create_unique_constraint(None, "report_signatures", ["diagnosis_entry_id"])
    op.drop_constraint(
        "report_signatures_report_id_fkey", "report_signatures", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "report_signatures", "doctor_diagnoses", ["diagnosis_entry_id"], ["id"]
    )
    op.drop_column("report_signatures", "report_id")
    op.drop_column("reports", "immunohistochemical_profile")
    op.drop_column("reports", "molecular_genetic_profile")
    op.drop_column("reports", "pathomorphological_diagnosis")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reports",
        sa.Column(
            "pathomorphological_diagnosis",
            sa.TEXT(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "reports",
        sa.Column(
            "molecular_genetic_profile", sa.TEXT(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "reports",
        sa.Column(
            "immunohistochemical_profile", sa.TEXT(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "report_signatures",
        sa.Column(
            "report_id", sa.VARCHAR(length=36), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "report_signatures", type_="foreignkey")
    op.create_foreign_key(
        "report_signatures_report_id_fkey",
        "report_signatures",
        "reports",
        ["report_id"],
        ["id"],
    )
    op.drop_constraint(None, "report_signatures", type_="unique")
    op.drop_column("report_signatures", "diagnosis_entry_id")
    op.drop_table("doctor_diagnoses")
    # ### end Alembic commands ###
