"""add app and device id  v1.1.12

Revision ID: c9476e916783
Revises: fc213fe91ee2
Create Date: 2025-08-21 10:04:02.024057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9476e916783'
down_revision: Union[str, None] = 'fc213fe91ee2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sessions', sa.Column('app_id', sa.String(length=250), nullable=True))
    op.add_column('user_sessions', sa.Column('device_id', sa.String(length=250), nullable=True))
    op.drop_constraint('uq_user_device_session', 'user_sessions', type_='unique')
    op.create_unique_constraint('uq_user_app_device_session', 'user_sessions', ['user_id', 'app_id', 'device_id'])
    op.create_unique_constraint('uq_user_device_session_legacy', 'user_sessions', ['user_id', 'device_info'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_device_session_legacy', 'user_sessions', type_='unique')
    op.drop_constraint('uq_user_app_device_session', 'user_sessions', type_='unique')
    op.create_unique_constraint('uq_user_device_session', 'user_sessions', ['user_id', 'device_info'])
    op.drop_column('user_sessions', 'device_id')
    op.drop_column('user_sessions', 'app_id')
    # ### end Alembic commands ###
