"""fix doctor diagnoses doctor id v1.0.8

Revision ID: cecef02c98dc
Revises: 0afcb3cae59b
Create Date: 2025-06-23 15:23:44.635709

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cecef02c98dc"
down_revision: Union[str, None] = "0afcb3cae59b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "doctor_diagnoses_doctor_id_fkey", "doctor_diagnoses", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "doctor_diagnoses", "doctors", ["doctor_id"], ["doctor_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "doctor_diagnoses", type_="foreignkey")
    op.create_foreign_key(
        "doctor_diagnoses_doctor_id_fkey",
        "doctor_diagnoses",
        "doctors",
        ["doctor_id"],
        ["id"],
    )
    # ### end Alembic commands ###
