"""add favotite flag

Revision ID: d17edc5eba47
Revises: 152eb2e2f061
Create Date: 2024-11-05 13:21:34.073659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd17edc5eba47'
down_revision: Union[str, None] = '152eb2e2f061'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('is_favorite', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records', 'is_favorite')
    # ### end Alembic commands ###
