"""rename surname  v1.0.0.42

Revision ID: d4eea16b7a69
Revises: eb072402e901
Create Date: 2025-06-12 14:18:27.232490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4eea16b7a69'
down_revision: Union[str, None] = 'eb072402e901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'doctors', 
        'surname', 
        new_column_name='middle_name', 
        existing_type=sa.String(length=100), 
        nullable=True 
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'doctors', 
        'middle_name', 
        new_column_name='surname', 
        existing_type=sa.String(length=100), 
        nullable=True 
    )
    # ### end Alembic commands ###
