"""add medicine intake times as JSONB  v1.1.18

Revision ID: df31f77e41ed
Revises: 398070ad6677
Create Date: 2025-10-08 10:54:15.410488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df31f77e41ed'
down_revision: Union[str, None] = '398070ad6677'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
    'medicine_schedules',
    'intake_times',
    existing_type=sa.VARCHAR(length=255),
    type_=postgresql.JSONB(),
    existing_nullable=True,
    postgresql_using="to_jsonb(string_to_array(intake_times, ','))"
)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('medicine_schedules', 'intake_times',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
