"""add lab assistants table  v1.0.0.41

Revision ID: eb072402e901
Revises: 06effa04a3ff
Create Date: 2025-06-11 15:49:08.212168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb072402e901'
down_revision: Union[str, None] = '06effa04a3ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab_assistants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lab_assistant_cor_id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('surname', sa.String(length=100), nullable=True),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('lab_assistants_photo', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['lab_assistant_cor_id'], ['users.cor_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lab_assistant_cor_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lab_assistants')
    # ### end Alembic commands ###
