"""add ecg_model  v1.1.7

Revision ID: eb10eade2363
Revises: 15d6aa4a9e45
Create Date: 2025-08-07 11:22:15.563823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb10eade2363'
down_revision: Union[str, None] = '15d6aa4a9e45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ecg_measurements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Дата и время сохранения записи в БД'),
    sa.Column('file_data', sa.LargeBinary(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ecg_measurements_user_id'), 'ecg_measurements', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ecg_measurements_user_id'), table_name='ecg_measurements')
    op.drop_table('ecg_measurements')
    # ### end Alembic commands ###
