"""add cassette str number v1.0.0.18

Revision ID: ed63d8af9674
Revises: 2e2be028f1e8
Create Date: 2025-04-29 15:09:09.855999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed63d8af9674'
down_revision: Union[str, None] = '2e2be028f1e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cassettes', 'cassette_number',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cassettes', 'cassette_number',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
