"""add referral unique case id  v1.0.0.34

Revision ID: f18ee07d4632
Revises: 92ca6a871f03
Create Date: 2025-05-23 12:42:19.739310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f18ee07d4632'
down_revision: Union[str, None] = '92ca6a871f03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'referrals', ['case_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'referrals', type_='unique')
    # ### end Alembic commands ###
