"""add doctor place of registration  v1.0.0.31

Revision ID: f92115dc9c34
Revises: 6b3808f33492
Create Date: 2025-05-19 10:29:47.085082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f92115dc9c34'
down_revision: Union[str, None] = '6b3808f33492'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('place_of_registration', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'place_of_registration')
    # ### end Alembic commands ###
