"""add OphthalmologicalPrescription table  v1.1.20

Revision ID: faf1a35189f5
Revises: 4a0a13100f2f
Create Date: 2025-10-09 10:24:17.741926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faf1a35189f5'
down_revision: Union[str, None] = '4a0a13100f2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ophthalmological_prescription',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=True),
    sa.Column('od_sph', sa.Float(), nullable=False),
    sa.Column('od_cyl', sa.Float(), nullable=False),
    sa.Column('od_ax', sa.Float(), nullable=False),
    sa.Column('od_prism', sa.Float(), nullable=False),
    sa.Column('od_base', sa.String(length=50), nullable=False),
    sa.Column('od_add', sa.Float(), nullable=False),
    sa.Column('os_sph', sa.Float(), nullable=False),
    sa.Column('os_cyl', sa.Float(), nullable=False),
    sa.Column('os_ax', sa.Float(), nullable=False),
    sa.Column('os_prism', sa.Float(), nullable=False),
    sa.Column('os_base', sa.String(length=50), nullable=False),
    sa.Column('os_add', sa.Float(), nullable=False),
    sa.Column('glasses_purpose', sa.String(length=50), nullable=False),
    sa.Column('glasses_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('note', sa.String(length=350), nullable=False),
    sa.Column('doctor_signature_id', sa.String(length=36), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_signature_id'], ['doctor_signatures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ophthalmological_prescription_patient_id'), 'ophthalmological_prescription', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ophthalmological_prescription_patient_id'), table_name='ophthalmological_prescription')
    op.drop_table('ophthalmological_prescription')
    # ### end Alembic commands ###
