"""add doctor signature id  v1.1.11

Revision ID: fc213fe91ee2
Revises: ae521c869e08
Create Date: 2025-08-18 14:57:26.089886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fc213fe91ee2'
down_revision: Union[str, None] = 'ae521c869e08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_signature_sessions', sa.Column('doctor_signature_id', sa.String(length=36), nullable=True))
    op.alter_column('doctor_signature_sessions', 'diagnosis_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('doctor_signature_sessions', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('doctor_signature_sessions', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('doctor_signature_sessions', 'diagnosis_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_column('doctor_signature_sessions', 'doctor_signature_id')
    # ### end Alembic commands ###
