"""add device models  v1.0.0.19

Revision ID: ff8978112354
Revises: ed63d8af9674
Create Date: 2025-05-05 10:57:38.236291

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ff8978112354"
down_revision: Union[str, None] = "ed63d8af9674"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "manufactured_devices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(), nullable=True),
        sa.Column("serial_number", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("MANUFACTURED", "ACTIVATED", "BLOCKED", name="devicestatus"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("serial_number"),
    )
    op.create_index(
        op.f("ix_manufactured_devices_id"), "manufactured_devices", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_manufactured_devices_token"),
        "manufactured_devices",
        ["token"],
        unique=True,
    )
    op.create_table(
        "devices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(), nullable=True),
        sa.Column("name", sa.String(length=250), nullable=True),
        sa.Column("create_date", sa.DateTime(), nullable=True),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.cor_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(op.f("ix_devices_id"), "devices", ["id"], unique=False)
    op.create_index(op.f("ix_devices_token"), "devices", ["token"], unique=True)
    op.create_table(
        "device_access",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=True),
        sa.Column("granting_user_id", sa.String(), nullable=True),
        sa.Column("accessing_user_id", sa.String(), nullable=True),
        sa.Column(
            "access_level",
            sa.Enum("READ", "READ_WRITE", "SHARE", name="accesslevel"),
            nullable=True,
        ),
        sa.Column("create_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["accessing_user_id"],
            ["users.cor_id"],
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["granting_user_id"],
            ["users.cor_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("accessing_user_id"),
        sa.UniqueConstraint("granting_user_id"),
    )
    op.create_index(op.f("ix_device_access_id"), "device_access", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_device_access_id"), table_name="device_access")
    op.drop_table("device_access")
    op.drop_index(op.f("ix_devices_token"), table_name="devices")
    op.drop_index(op.f("ix_devices_id"), table_name="devices")
    op.drop_table("devices")
    op.drop_index(
        op.f("ix_manufactured_devices_token"), table_name="manufactured_devices"
    )
    op.drop_index(op.f("ix_manufactured_devices_id"), table_name="manufactured_devices")
    op.drop_table("manufactured_devices")
    # ### end Alembic commands ###
